# UCS Demo
name: Worker Service Building Process For UCS CICD Demo.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "Now, Building image for Worker service. "
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: | 
        docker build -f worker/Dockerfile.j -t worker:latest .     
    - run: |
        sudo docker tag worker:latest swr.ap-southeast-3.myhuaweicloud.com/ucs/worker:latest
