# UCS Demo
name: UCS CICD Demo For Phoniex Store Web Service
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "Now, Building image for vote service. "
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        cd vote
        yarn install
    - name: Build
      run: | 
        docker build -t ucs-vote .

